/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yahoo_example_test_SampleJni */

#ifndef _Included_com_yahoo_example_test_SampleJni
#define _Included_com_yahoo_example_test_SampleJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yahoo_example_test_SampleJni
 * Method:    nativeSampleInfo
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_example_test_SampleJni_nativeSampleInfo
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_yahoo_example_test_SampleJni
 * Method:    put4Bytes
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_example_test_SampleJni_put4Bytes
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
