/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yahoo_example_testutf8_JNITest */

#ifndef _Included_com_yahoo_example_testutf8_JNITest
#define _Included_com_yahoo_example_testutf8_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yahoo_example_testutf8_JNITest
 * Method:    dumpDecodedBytes
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_example_testutf8_JNITest_dumpDecodedBytes
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
