/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "com_yahoo_example_test_TestReleaseNull.h"

/*
 * Class:     com_yahoo_example_test_TestReleaseNull
 * Method:    testString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_example_test_TestReleaseNull_testString
(JNIEnv *jenv, jclass, jstring jstr)
{

}

/*
 * Class:     com_yahoo_example_test_TestReleaseNull
 * Method:    testByte
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_example_test_TestReleaseNull_testByte
(JNIEnv *jenv, jclass, jbyteArray array, int mode)
{
    jbyte *data = jenv->GetByteArrayElements(array, NULL);
    if (data==NULL || jenv->ExceptionCheck()) {
        return;
    }

    jenv->ReleaseByteArrayElements(NULL, data, mode);
}
