/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yahoo_example_test_DecodeTest */

#ifndef _Included_com_yahoo_example_test_DecodeTest
#define _Included_com_yahoo_example_test_DecodeTest
#ifdef __cplusplus
extern "C" {
#endif
#undef com_yahoo_example_test_DecodeTest_data
#define com_yahoo_example_test_DecodeTest_data -2401053089206452208LL
/*
 * Class:     com_yahoo_example_test_DecodeTest
 * Method:    dump
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_yahoo_example_test_DecodeTest_dump
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_yahoo_example_test_DecodeTest
 * Method:    dumpEncoded
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_yahoo_example_test_DecodeTest_dumpEncoded
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_yahoo_example_test_DecodeTest
 * Method:    encodeInto
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_example_test_DecodeTest_encodeInto
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
