/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yahoo_example_test_TestReleaseNull */

#ifndef _Included_com_yahoo_example_test_TestReleaseNull
#define _Included_com_yahoo_example_test_TestReleaseNull
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yahoo_example_test_TestReleaseNull
 * Method:    testString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_example_test_TestReleaseNull_testString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_yahoo_example_test_TestReleaseNull
 * Method:    testByte
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_example_test_TestReleaseNull_testByte
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
