/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yahoo_wildwest_PowersawValidator */

#ifndef _Included_com_yahoo_wildwest_PowersawValidator
#define _Included_com_yahoo_wildwest_PowersawValidator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yahoo_wildwest_PowersawValidator
 * Method:    validateIpv4
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_yahoo_wildwest_PowersawValidator_validateIpv4
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_yahoo_wildwest_PowersawValidator
 * Method:    validateIpv6
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_yahoo_wildwest_PowersawValidator_validateIpv6
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_yahoo_wildwest_PowersawValidator
 * Method:    validateAddresses
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_yahoo_wildwest_PowersawValidator_validateAddresses
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
