/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yahoo_test_strings_JNIStrings */

#ifndef _Included_com_yahoo_test_strings_JNIStrings
#define _Included_com_yahoo_test_strings_JNIStrings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yahoo_test_strings_JNIStrings
 * Method:    jniString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yahoo_test_strings_JNIStrings_jniString
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_yahoo_test_strings_JNIStrings
 * Method:    encodedString
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_yahoo_test_strings_JNIStrings_encodedString
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_yahoo_test_strings_JNIStrings
 * Method:    freeString
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_test_strings_JNIStrings_freeString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_yahoo_test_strings_JNIStrings
 * Method:    unsafeString
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_test_strings_JNIStrings_unsafeString
  (JNIEnv *, jclass, jint, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
