/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yahoo_example_test_SampleJniTest */

#ifndef _Included_com_yahoo_example_test_SampleJniTest
#define _Included_com_yahoo_example_test_SampleJniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yahoo_example_test_SampleJniTest
 * Method:    nativeSampleInfo
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_example_test_SampleJniTest_nativeSampleInfo
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
